### ISSUE TITLE
自定义dubbo过滤器，打成jar包之后 提示找不到Filter的实现。 

### ISSUE THREAD

**Issue by pandajava** [crossoverJie/SSM-DUBBO-FILTER#1]
按照你的做法将filter单独jar包，所有的dubbo接口 都使用了这个过滤器，有些场景 想过滤器 对某些接口起作用。
A 接口配置   dubbo:service   中  filter="dubboTraceFilter"  ，B接口不配置。
实际都起作用了 。请教这种情况如何处理 让dubboTraceFilter对  B接口 不生效？ 

-----------------------------
在程序内部写一个Filter 程序运行没问题 打成jar包  提示  找不到 Filter 接口的实现。  META-INF/dubbo/xxxx.xxx.xx.xx.rpc.Filter都配置了  打包也打进去了 。
疑惑中。。。求解答

**Comment by crossoverJie** [comment]
sorry, 许久没用dubbo了,对于提供的spi也不是很熟了。

但是如果你是想只过滤一部分接口，可以增加一个配置文件其中配置要拦截或者是不拦截的接口和方法。

https://github.com/crossoverJie/SSM-DUBBO-FILTER/blob/e806ee36f7710f5919ec05ec719c01707480fb4d/SSM-TRACE-FILTER/src/main/java/com/crossoverJie/dubbo/filter/DubboTraceFilter.java#L26-L27

在这里可以根据配置的进行判断是否走后面的逻辑，不过这样效率可能有点低，毕竟还是每个接口、方法偶读拦截了。

> 以上仅供参考。

**Comment by crossoverJie** [comment]
参考官方文档:

[https://dubbo.gitbooks.io/dubbo-dev-book/impls/filter.html](https://dubbo.gitbooks.io/dubbo-dev-book/impls/filter.html)

**Comment by pandajava** [comment]
按照官方文档来的，本地运行可以，打成jar包就找不到Filter的实现，可能是打包方式有问题。

**Comment by pandajava** [comment]
按照官方文档来的，本地运行可以，打成jar包就找不到Filter的实现，可能是打包方式有问题。
打的包里面  确实是有  META-INF/dubbo/xxxx.xxx.xx.xx.rpc.Filter这个配置。

非常感谢3Q

**Comment by JunjianS** [comment]
楼主问题解决了吗？？？求解决方案

**Comment by crossoverJie** [comment]
@JunjianS 暂时没有用 dubbo 了，之后有需求会更新。
